name: Deploy to Testflight on:
  release:
    types: [created]jobs:
  deploy:
    name: Deploy
    runs-on: macos-latest
      
    steps:      
    - name: Checkout
      uses: actions/checkout@v2    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
      
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    
    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
        bundler-cache: true
        
    - name: Install Pods
      run: pod install
            
    - name: Build & Distribute to Testflight 
      run: |
        export LC_ALL=en_US.UTF-8
        export LANG=en_US.UTF-8
        ./decrypt_secret.sh
        bundle exec fastlane set_release_version 
        bundle exec fastlane beta
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }
        RELEASE_VERSION: ${{ github.event.release.tag_name }}
        APPSTORE_AUTHKEY: ${{ secrets.APPSTORE_AUTHKEY }}
        CHANGELOG: ${{ github.event.release.body }}